# stubs/pyttsx3-stubs/__init__.pyi
from typing import Any

def init() -> "Engine": ...

class Engine:
    def say(self, text: str) -> None: ...
    def runAndWait(self) -> None: ...
    def setProperty(self, name: str, value: Any) -> None: ...
    def getProperty(self, name: str) -> Any: ...