# stubs/pandas-stubs/__init__.pyi
from typing import Any

def read_csv(filepath_or_buffer: Any, **kwargs) -> "DataFrame": ...

class DataFrame:
    def to_dict(self, orient: str = "dict") -> dict: ...
    def to_json(self, path_or_buf: Any = None, orient: str = "records") -> str: ...