# stubs/scapy-stubs/__init__.pyi
from typing import Any

def rdpcap(filename: str) -> Any: ...

class IP: ...
class ICMP: ...
class TCP: ...
class UDP: ...
class Ether: ...
class ARP: ...
class DNS: ...
class DNSQR: ...
class HTTP: ...
class Raw: ...

def sr1(pkt: Any, timeout: int = 2) -> Any: ...
def srp(pkt: Any, timeout: int = 2) -> tuple[Any, Any]: ...
