# stubs/rank_bm25-stubs/__init__.pyi
class BM25Okapi:
    def __init__(self, corpus: list[list[str]]) -> None: ...
    def get_scores(self, query: list[str]) -> list[float]: ...
    def get_top_n(self, query: list[str], documents: list[str], n: int = 5) -> list[str]: ...