# stubs/speech_recognition-stubs/__init__.pyi
from typing import Optional

class Recognizer:
    def __init__(self) -> None: ...
    def recognize_google(self, audio_data: "AudioData", language: str = "ru-RU") -> str: ...
    def listen(self, source: "Microphone", timeout: Optional[float] = None) -> "AudioData": ...

class Microphone:
    def __init__(self, device_index: Optional[int] = None) -> None: ...
    def __enter__(self) -> "Microphone": ...
    def __exit__(self, *args) -> None: ...

class AudioData: ...