networks:
  ct_lab_net:
    driver: bridge
services:
  dvwa:
    container_name: ct_dvwa
    image: vulnerables/web-dvwa:latest
    networks:
    - ct_lab_net
    ports:
    - 8080:80
    restart: unless-stopped
version: '3.8'
