# stubs/streamlit-stubs/__init__.pyi
from typing import Any, Callable, Dict

def set_page_config(**kwargs) -> None: ...
def title(text: str) -> None: ...
def markdown(body: str) -> None: ...
def write(text: str) -> None: ...
def text_input(label: str, value: str = "") -> str: ...
def selectbox(label: str, options: list, index: int = 0) -> Any: ...
def button(label: str) -> bool: ...
def form(key: str) -> Any: ...
def form_submit_button(label: str) -> bool: ...
def columns(spec: list) -> list: ...
def container() -> Any: ...
def expander(label: str) -> Any: ...
def success(body: str) -> None: ...
def info(body: str) -> None: ...
def warning(body: str) -> None: ...
def error(body: str) -> None: ...
def exception(e: Exception) -> None: ...
def spinner(text: str) -> Any: ...
def progress(value: float) -> Any: ...
def cache_resource(func: Callable) -> Callable: ...
def cache_data(func: Callable) -> Callable: ...

class _Sidebar:
    def markdown(self, body: str) -> None: ...
    def selectbox(self, label: str, options: list) -> Any: ...
    def slider(self, label: str, min_value: float, max_value: float, value: float) -> float: ...

sidebar: _Sidebar = ...
session_state: Dict[str, Any] = ...