"""add learning_events table

Revision ID: cb007d8d52d1
Revises: 8ff380d95f4a
Create Date: 2026-09-18 22:33:33.092226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb007d8d52d1'
down_revision: Union[str, Sequence[str], None] = '8ff380d95f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('user_belief', sa.Text(), nullable=True),
    sa.Column('correct_model', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.String(length=200), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('context_ref', sa.String(length=200), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_events_event_type', 'learning_events', ['event_type'], unique=False)
    op.create_index('ix_learning_events_root_cause', 'learning_events', ['root_cause'], unique=False)
    op.create_index('ix_learning_events_timestamp', 'learning_events', ['timestamp'], unique=False)
    op.create_index('ix_learning_events_topic', 'learning_events', ['topic'], unique=False)
    op.create_index('ix_learning_events_user_id', 'learning_events', ['user_id'], unique=False)
    op.create_index('ix_achievements_earned', 'achievements', ['earned'], unique=False)
    op.create_index('ix_achievements_earned_at', 'achievements', ['earned_at'], unique=False)
    op.create_index('ix_command_heatmap_command', 'command_heatmap', ['command'], unique=False)
    op.create_index('ix_command_heatmap_date', 'command_heatmap', ['date'], unique=False)
    op.create_index('ix_daily_challenges_completed', 'daily_challenges', ['completed'], unique=False)
    op.create_index('ix_daily_challenges_date', 'daily_challenges', ['date'], unique=False)
    op.create_index('ix_exploit_log_cve_id', 'exploit_log', ['cve_id'], unique=False)
    op.create_index('ix_exploit_log_timestamp', 'exploit_log', ['timestamp'], unique=False)
    op.create_index('ix_flags_captured', 'flags', ['captured'], unique=False)
    op.create_index('ix_flags_captured_at', 'flags', ['captured_at'], unique=False)
    op.create_index('ix_flags_category', 'flags', ['category'], unique=False)
    op.create_index('ix_messages_mode', 'messages', ['mode'], unique=False)
    op.create_index('ix_messages_timestamp_role', 'messages', ['timestamp', 'role'], unique=False)
    op.create_index('ix_progress_last_seen', 'progress', ['last_seen'], unique=False)
    op.create_index('ix_purchase_history_item_id', 'purchase_history', ['item_id'], unique=False)
    op.create_index('ix_purchase_history_purchased_at', 'purchase_history', ['purchased_at'], unique=False)
    op.create_index('ix_query_cache_created_at', 'query_cache', ['created_at'], unique=False)
    op.create_index('ix_query_cache_expires_at', 'query_cache', ['expires_at'], unique=False)
    op.create_index('ix_review_schedule_next_review', 'review_schedule', ['next_review'], unique=False)
    op.create_index('ix_review_schedule_topic', 'review_schedule', ['topic'], unique=False)
    op.create_index('ix_session_summary_start_time', 'session_summaries', ['start_time'], unique=False)
    op.create_index('ix_skills_last_practice', 'skills', ['last_practice'], unique=False)
    op.create_index('ix_writeups_created_at', 'writeups', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_writeups_created_at', table_name='writeups')
    op.drop_index('ix_skills_last_practice', table_name='skills')
    op.drop_index('ix_session_summary_start_time', table_name='session_summaries')
    op.drop_index('ix_review_schedule_topic', table_name='review_schedule')
    op.drop_index('ix_review_schedule_next_review', table_name='review_schedule')
    op.drop_index('ix_query_cache_expires_at', table_name='query_cache')
    op.drop_index('ix_query_cache_created_at', table_name='query_cache')
    op.drop_index('ix_purchase_history_purchased_at', table_name='purchase_history')
    op.drop_index('ix_purchase_history_item_id', table_name='purchase_history')
    op.drop_index('ix_progress_last_seen', table_name='progress')
    op.drop_index('ix_messages_timestamp_role', table_name='messages')
    op.drop_index('ix_messages_mode', table_name='messages')
    op.drop_index('ix_flags_category', table_name='flags')
    op.drop_index('ix_flags_captured_at', table_name='flags')
    op.drop_index('ix_flags_captured', table_name='flags')
    op.drop_index('ix_exploit_log_timestamp', table_name='exploit_log')
    op.drop_index('ix_exploit_log_cve_id', table_name='exploit_log')
    op.drop_index('ix_daily_challenges_date', table_name='daily_challenges')
    op.drop_index('ix_daily_challenges_completed', table_name='daily_challenges')
    op.drop_index('ix_command_heatmap_date', table_name='command_heatmap')
    op.drop_index('ix_command_heatmap_command', table_name='command_heatmap')
    op.drop_index('ix_achievements_earned_at', table_name='achievements')
    op.drop_index('ix_achievements_earned', table_name='achievements')
    op.drop_index('ix_learning_events_user_id', table_name='learning_events')
    op.drop_index('ix_learning_events_topic', table_name='learning_events')
    op.drop_index('ix_learning_events_timestamp', table_name='learning_events')
    op.drop_index('ix_learning_events_root_cause', table_name='learning_events')
    op.drop_index('ix_learning_events_event_type', table_name='learning_events')
    op.drop_table('learning_events')
    # ### end Alembic commands ###
