"""add importance to learning_events

Revision ID: d293c1233d00
Revises: cb007d8d52d1
Create Date: 2026-09-20 10:22:11.554643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd293c1233d00'
down_revision: Union[str, Sequence[str], None] = 'cb007d8d52d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_events', sa.Column('importance', sa.Float(), nullable=False, server_default=sa.text('0.5')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_events', 'importance')
    # ### end Alembic commands ###
