# stubs/faiss-stubs/__init__.pyi
from typing import Any

def read_index(fname: str) -> Any: ...
def write_index(idx: Any, fname: str) -> None: ...
class IndexFlatL2:
    def __init__(self, d: int) -> None: ...
    def add(self, x: Any) -> None: ...
    def search(self, x: Any, k: int) -> tuple[Any, Any]: ...