# stubs/lxml-stubs/etree.pyi
from typing import Any

def parse(source: Any) -> "ElementTree": ...

class ElementTree:
    def getroot(self) -> "Element": ...

class Element:
    def findall(self, path: str) -> list["Element"]: ...
    def findtext(self, path: str, default: str = "") -> str: ...
    def get(self, key: str, default: str = "") -> str: ...
    @property
    def text(self) -> str: ...