# stubs/pymetasploit3-stubs/__init__.pyi
class MsfRpcClient:
    def __init__(self, password: str, port: int = 55553, ssl: bool = False, server: str = "127.0.0.1", uri: str = "/api/") -> None: ...
    def login(self) -> bool: ...
    def call(self, module: str, method: str, **kwargs) -> dict: ...